---
title: "Decisions"
toc: true
listing:
  filter-ui: false
  type: table
  contents:
    - "decisions/*.md"
  sort: "filename desc"
  feed: true
  fields: [filename, title, image, reading-time]
---
      # [short title of solved problem and solution]
      - Status: proposed <!-- draft | rejected | accepted | deprecated | superseded by -->
      - Deciders: V-Sekai,
      - Tags: V-Sekai,
      ## Context and Problem Statement <!-- Describe the problem or limitation you are having in your project -->
      [Describe the context and problem statement, e.g., in free form using two to three sentences. You may want to articulate the problem in the form of a question.]
      ## Describe the proposed option and how it helps to overcome the problem or limitation
      ## Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams
      ## Positive Consequences <!-- optional - e.g., improvement of quality attribute satisfaction, follow-up decisions required, … -->
      ## Negative Consequences <!-- optional - e.g., compromising quality attribute, follow-up decisions required, … -->
      ## Option graveyard: <!-- same as above -->
      - Option: <!-- [List the proposed options no longer open for consideration.] -->
      - Rejection Reason: <!-- [List the reasons for the rejection: (the Bad traits)] -->
      ## If this enhancement will not be used often, can it be worked around with a few lines of script?
      [If this enhancement will not be used often, can it be worked around with a few lines of script?]
      ## Is there a reason why this should be core and done by us?
      [Is there a reason why this should be core and done by us?]
      ## References <!-- optional and numbers of links can vary -->
      - [V-Sekai](https://v-sekai.org/)