name: Feature / Enhancement proposal
description: Open a new proposal
body:
  - type: markdown
    attributes:
      value: |
        - Write a descriptive proposal title above.
        - Search [open](https://github.com/V-Sekai/v-sekai-proposals/issues) and [closed](https://github.com/V-Sekai/v-sekai-proposals/issues?q=is%3Aissue+is%3Aclosed) proposals to ensure the feature has not already been suggested.

  - type: textarea
    attributes:
      label: Proposal Title
      placeholder: Proposal Title
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context and Problem Statement
      placeholder: Context and Problem Statement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the feature / enhancement and how it helps to overcome the problem or limitation
      placeholder: Describe the proposed option and how it helps to overcome the problem or limitation
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
      placeholder: Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams
    validations:
      required: true

  - type: textarea
    attributes:
      label: If this enhancement will not be used often, can it be worked around with a few lines of script?
      placeholder: Is there a reason why this should be core and done by us?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Positive Consequences
      placeholder: For example, improvement of quality attribute satisfaction, follow-up decisions required
    validations:
      required: false

  - type: textarea
    attributes:
      label: Negative Consequences
      placeholder: For example, compromising quality attribute, follow-up decisions required
    validations:
      required: false

  - type: textarea
    attributes:
      label: Is there a reason why this should be core and done by us?
      placeholder: If this enhancement will not be used often, can it be worked around with a few lines of script?
    validations:
      required: true

  - type: textarea
    attributes:
      label: References
      placeholder: |
        - [Link type](link to decision) <!-- example: Refined by [xxx](yyyymmdd-xxx.md) -->
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Derivative License
      options: 
       - |
        Copyright (c) 2020-2021 V-Sekai contributors.

        Permission is hereby granted, free of charge, to any person obtaining a copy
        of this software and associated documentation files (the "Software"), to deal
        in the Software without restriction, including without limitation the rights
        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        copies of the Software, and to permit persons to whom the Software is
        furnished to do so, subject to the following conditions:

        The above copyright notice and this permission notice shall be included in all
        copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
        SOFTWARE.
    validations:
      required: true
